<?php

/**
 * @file
 * Contains feedback.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\user\RoleInterface;
use Drupal\Core\Render\Element;

/**
 * Implements hook_help().
 */
function feedback_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the feedback module.
    case 'help.page.feedback':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function feedback_theme() {
  return [
    'feedback' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for Feedback templates.
 *
 * Default template: feedback.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the user information and any
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_feedback(array &$variables) {
  // Fetch Feedback Entity Object.
  $feedback = $variables['elements']['#feedback'];

  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
