<?php

/**
 * @file
 * Contains feedback.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\user\RoleInterface;

/**
 * Implements hook_help().
 */
function feedback_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the feedback module.
    case 'help.page.feedback':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function feedback_theme() {
  return [
    'feedback' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_install().
 */
function feedback_install()
{
    // 为已认证用户添加权限
    user_role_grant_permissions(RoleInterface::AUTHENTICATED_ID, [
        'add feedback entities',
        'restful post feedback_make_feedback'
    ]);
}
